[build]
  CI= "npm run build"
  publish = "dist"
  NODE_ENV = "20.11.0"


[dev]
  CI= "npm run build"


[build.processing.html]
  pretty_urls = true


[[redirects]]
  from = "/assets/img/:file"
  to = "/.netlify/images?url=/assets/img/:file"
  status = 200

[[redirects]]
  from = "assets/img/:width/:file"
  to = "/.netlify/images?url=/assets/img/:file&width=:width"
  status = 200

[[redirects]]
  from = "/kontakt"
  to = "/kontakt-anfahrt"
  status = 301
  force = true

[[redirects]]
  from = "/arzte"
  to = "/team"
  status = 301
  force = true


[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"

  exclude = [
    "./dist/index.html",    # extra safe
  ]